[workspace]
members = [
  "hello-world",
  "reverse-string",
  "gigasecond",
  "clock",
  "anagram",
  "space-age",
  "sublist",
  "flower-field",
  "luhn",
  "armstrong-numbers",
  "beer-song",
  "bottle-song",
]
resolver = "3"

[workspace.dependencies]
unicode-segmentation = "1.3.0"
time = "0.3"
