[workspace]
members = [
  "hello-world",
  "reverse-string",
  "gigasecond",
  "clock",
  "anagram",
  "space-age"
]
resolver = "3"

[workspace.dependencies]
unicode-segmentation = "1.3.0"
time = "0.3"
